What's New on CPAN for November 2023
perladvent/perldotcom pull request #350
Opened 2023-12-21 21:15 UTC by matstar2

New article plus some changes to DF's script for article scaffolding (probably should have excluded that?)

2023-12-22 15:13 UTC, oalders requested changes
\o/ 

It's great to see this back. I just had a couple of comments.

2023-12-22 15:13 UTC, oalders commented on bin/format-cpan-uploads
> +    #$module{description} = $descriptions[ int rand @descriptions ];
I think rather than commenting out code, we can delete it. It's easy enough to revert changes since they're tracked by `git` anyway.

2023-12-22 15:13 UTC, oalders commented on bin/format-cpan-uploads
> +    #}
Why is this commented out?

2023-12-22 23:40 UTC, matstar2 commented
Hi Olaf, that bit I commented out gives interactive category override before rendering the article. I found that I prefer doing those edits in markdown.

Mat

On Dec 22, 2023 4:13 p.m., Olaf Alders ***@***.***> wrote:
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@oalders requested changes on this pull request.

\o/

It's great to see this back. I just had a couple of comments.

________________________________

In bin/format-cpan-uploads<https://github.com/perladvent/perldotcom/pull/350#discussion_r1435147686>:

> @@ -71,10 +71,11 @@ for my $release (sort @lines)
       sprintf('%s %s', $module{mcpan_link}, $module{description}),
       sprintf('%s can %s', $module{mcpan_link}, $module{description}),
     );
-    $module{description} = $descriptions[ int rand @descriptions ];
+    #$module{description} = $descriptions[ int rand @descriptions ];


I think rather than commenting out code, we can delete it. It's easy enough to revert changes since they're tracked by git anyway.

________________________________

In bin/format-cpan-uploads<https://github.com/perladvent/perldotcom/pull/350#discussion_r1435149151>:

> -    {
-      next unless $answer =~ /^\d$/ && $answer < @categories;
-      $module{category} = $categories[$answer];
-    }
+    #for (sort keys %categories)
+    #{
+    #  my $current = $module{category} eq $_ ? '*' : ' ';
+    #  push @categories, $_;
+    #  printf " %s[%u] %s\n", $current, @categories - 1, $_;
+    #}
+    #my $answer = <<>>; chomp $answer;
+    #if ($answer)
+    #{
+    #  next unless $answer =~ /^\d$/ && $answer < @categories;
+    #  $module{category} = $categories[$answer];
+    #}


Why is this commented out?

—
Reply to this email directly, view it on GitHub<https://github.com/perladvent/perldotcom/pull/350#pullrequestreview-1794616116>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHPZ2LREFU4QO5SRLBBSWK3YKWPSDAVCNFSM6AAAAABA663M4CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJUGYYTMMJRGY>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-12-23 16:10 UTC, oalders commented
@rwp0 do you have permissions to merge this pull request?

2023-12-23 16:11 UTC, rwp0 commented
> @rwp0 do you have permissions to merge this pull request?

Unfortunately, no.

![image](https://github.com/perladvent/perldotcom/assets/68062695/d5560173-1229-4910-8e27-4d388e788c7a)

2023-12-23 16:11 UTC, oalders commented
@matstar2 I think it would be best to have the article in one commit and the changes to the script in a different commit. That would make it easier to roll back the changes to the script later if we needed to.

2023-12-25 20:36 UTC, closed without merging

2023-12-25 20:47 UTC, rwp0 commented
@matstar2 Could you please tell us why did you close this PR?

2023-12-25 20:49 UTC, matstar2 commented
Hi, I am replacing it with another one. Coming in a moment...

Mat

On 2023-12-25 3:48 p.m., Elvin Aslanov wrote:
>
> 	
> You don't often get email from ***@***.*** Learn why 
> this is important <https://aka.ms/LearnAboutSenderIdentification>
> 	
>
> @matstar2 <https://github.com/matstar2> Could you please tell us why 
> did you close this PR?
>
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/perladvent/perldotcom/pull/350#issuecomment-1869113446>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AHPZ2LWREEMQQJBCVH2LEGLYLHRABAVCNFSM6AAAAABA663M4CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNRZGEYTGNBUGY>.
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>
>