update scripts and new article
perladvent/perldotcom pull request #365
Opened 2024-05-08 03:22 UTC by matstar2

Changes to "What's New on CPAN" related-scripts:
- PAUSE id's get added to articles
- Personalization and workflow preferences
- Additional patterns for module categorization
What's New on CPAN for April 2024

2024-05-08 13:14 UTC, oalders commented
Looks like the actual article URL is https://www-perl-com-pr-365.onrender.com/article/what-s-new-on-cpan-april-2024/

We should fix the render.com build not to hardcode the hostname in the urls.

2024-05-08 13:22 UTC, oalders requested changes
Looks great! Just a few comments to look at.

2024-05-08 13:22 UTC, oalders commented on bin/format-cpan-uploads
> +    #print "$i/$total $module{name} - accept category or select another:\n";
Delete?

2024-05-08 13:22 UTC, oalders commented on bin/format-cpan-uploads
> +  thumbnail   => "/images/176/thumb_2A6DE1D0-0ACE-11E5-A57F-EAC87F6D3C83.png",
👍🏻 It looks like David was switching between colours in his posts, but I think this is good.

2024-05-08 13:22 UTC, oalders commented on bin/get-cpan-uploads
> +use Data::Dump qw/dump/;
Since this is unused it can be deleted.

2024-05-08 13:22 UTC, oalders commented on bin/get-cpan-uploads
> +  #say STDERR dump $release->{metadata}{author};
This can be deleted.

2024-05-08 13:22 UTC, oalders commented on content/article/what-s-new-on-cpan---april-2024.md
> +* [Dist::Build](https://metacpan.org/pod/Dist::Build) (LEONT) provides another way to build and install Perl modules* [Dist::Build](https://metacpan.org/pod/Dist::Build) (LEONT) provides another way
```suggestion
* [Dist::Build](https://metacpan.org/pod/Dist::Build) (LEONT) provides another way to build and install Perl modules
```

2024-05-08 13:22 UTC, oalders commented on content/article/what-s-new-on-cpan---april-2024.md
> +* Stingify references in:
```suggestion
* Stringify references in:
```

2024-05-08 17:04 UTC, oalders commented on bin/format-cpan-uploads
> +#END { unlink '.tmp.pod' } #don't need to cleanup since we're not using this file
> It also occurs to me that I should have further subdivided those script changes into commits of their own.

That's always helpful. 😄 They could even live in their own PR, but I wouldn't worry too much about it today. It's nice just to see activity on this repository.

2024-05-09 21:41 UTC, matstar2 commented on bin/get-cpan-uploads
> +  #say STDERR dump $release->{metadata}{author};
Done

2024-05-09 21:41 UTC, matstar2 commented on bin/get-cpan-uploads
> +use Data::Dump qw/dump/;
Done

2024-05-09 21:41 UTC, matstar2 commented on bin/format-cpan-uploads
> +    #print "$i/$total $module{name} - accept category or select another:\n";
Done

2024-05-09 21:41 UTC, matstar2 commented on bin/format-cpan-uploads
Done

2024-05-09 21:42 UTC, matstar2 commented on bin/format-cpan-uploads
> +#END { unlink '.tmp.pod' } #don't need to cleanup since we're not using this file
Done

2024-05-09 21:43 UTC, matstar2 commented
I believe this is now ready to go

2024-05-09 22:52 UTC, oalders approved these changes
🎉

2024-05-09 22:52 UTC, merged

2024-05-11 11:58 UTC, mohawk2 commented
I had a read of the March and April articles. I appreciate that it's curated and therefore this may have been a conscious choice, but while there was lots of PERLANCAR modules, there were no PDL modules shown (there was a release of actual PDL in both months, along with various other modules). Is that deliberate?

2024-05-11 12:09 UTC, oalders commented
The What's New list is a list of first ever releases for modules. Were the PDL releases being uploaded for the very first time in that namespace?

It might be helpful to include noteworthy modules that have also been released but that's not traditionally with this article has been.

2024-05-11 18:43 UTC, mohawk2 commented
Ah, sorry for my confusion - I read "what's new" as including "a new version", not "completely new distro". It might make sense to emphasise that in some way to help the hard of understanding :-)